name = "qatar-nas-system"
type = "javascript"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[env.production]
name = "qatar-nas-system-prod"

[build]
command = "pnpm build"
cwd = "./"

[assets]
directory = "dist"
binding = "__STATIC_CONTENT_MANIFEST"
